# Generated by Django 4.0.3 on 2022-03-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_rename_starupper_id_startup_startupper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='startup',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('Ecology', 'Ecology'), ('Electronic', 'Electronic'), ('Health', 'Health'), ('Education', 'Education'), ('Gaming', 'Gaming'), ('Small Business', 'Small Business'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
