# Generated by Django 4.0.3 on 2022-03-31 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_categories_startup_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
