# Generated by Django 4.0.3 on 2022-03-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userinvestor_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestor',
            name='current_money',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
