# Generated by Django 4.0.3 on 2022-03-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userinvestor_current_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestor',
            name='current_money',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
